dionaShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as OrderViews
from user import views as UserViews

urlpatterns = [

                  path('', include('home.urls')),
                  path('home/', include('home.urls')),
                  path('product/', include('product.urls')),
                  path('order/', include('order.urls')),
                  path('user/', include('user.urls')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('admin/', admin.site.urls),

                  path('services/', views.services, name='services'),
                  path('about/', views.about, name='about'),
                  path('delivery/', views.delivery, name='delivery'),
                  # path('contact/', views.contact, name='contact'),
                  path('search/', views.search, name='search'),
                  # path('search_auto/', views.search_auto, name='search_auto'),
                  path('all_products/', views.all_products, name='all_products'),
                  # path('sorted_product/', views.sorted_product, name='sorted_product'),
                  path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
                  path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
                  path('shopcart/', OrderViews.shopcart, name='shopcart'),
                  path('login/', UserViews.login_form, name='login_form'),
                  path('logout/', UserViews.logout_func, name='logout_func'),
                  path('signup/', UserViews.signup_form, name='signup_form'),
                  path('faq/', views.faq, name='faq'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

order/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('changefromcart/<int:id>', views.changefromcart, name='changefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

order/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm, forms

from product.models import Product


# Create your models here.


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    price = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()

    def __str__(self):
        return self.product.title

    # @property
    # def price(self):
    #     return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.price)

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity', 'price', 'width', 'height']



class Order(models.Model):
    STATUS = (
        ('Новый', 'Новый'),
        ('Принят', 'Принят'),
        ('Собирается', 'Собирается'),
        ('Передан в доставку', 'Передан в доставку'),
        ('Доставлен', 'Доставлен'),
        ('Отменён', 'Отменён'),
    )

    DELIVERY = (
        ('Курьер', 'Курьер'),
        ('Самовывоз', 'Самовывоз'),
    )

    PAY = (
        ('Картой онлайн', 'Картой онлайн'),
        ('При получении', 'При получении'),

    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, unique=True)
    first_name = models.CharField(blank=False, max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=False, max_length=20)
    email = models.CharField(blank=False, max_length=50)
    address = models.CharField(blank=False, max_length=150)
    city = models.CharField(blank=False, max_length=20)
    delivery = models.CharField(blank=False,max_length=20, choices=DELIVERY, default='Курьер')
    pay = models.CharField(blank=False,max_length=50, choices=PAY, default='Картой онлайн')
    total = models.FloatField()
    status = models.CharField(max_length=20, choices=STATUS, default='Новый')
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'email', 'delivery', 'pay']


class OrderProduct(models.Model):
    STATUS = (
        ('Новый', 'Новый'),
        ('Принят', 'Принят'),
        ('Отменён', 'Отменён'),
    )



    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()
    price = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()
    amount = models.FloatField()
    status = models.CharField(max_length=20, choices=STATUS, default='Новый')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

    class Meta:
        verbose_name = 'Заказанный товар'
        verbose_name_plural = 'Заказанные товары'

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.utils.crypto import get_random_string


from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Category, Product
from user.models import UserProfile


def index(request):
    category = Category.objects.all()
    context = {
        'category':category,
    }
    return HttpResponse("Page order")


@login_required(login_url='/login')  # Check login
def addtoshopcart(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information
    # product= Product.objects.get(pk=id)

    checkinproduct = ShopCart.objects.filter(product_id=id)  # Check product in shopcart
    if checkinproduct:
        control = 1  # The product is in the cart
    else:
        control = 0  # The product is not in the cart"""



    if request.method == 'POST':

        # if control == 1:
        #     data = ShopCart.objects.get(product_id=id)
        #     data.quantity += int(request.POST['quantity'])
        #     data.save()
        # else:
        data = ShopCart()
        data.user_id = current_user.id
        data.product_id = id
        data.quantity = int(request.POST['quantity'])
        data.price = int(request.POST['product_price'])
        data.width = int(request.POST['width_rome'])
        data.height = int(request.POST['height_rome'])
        data.save()
        messages.success(request, "Товар добавлен в корзину ")
        return HttpResponseRedirect(url)

    # else:  # if there is no post
    #     if control == 1:  # Update  shopcart
    #         data = ShopCart.objects.get(product_id=id)
    #         data.quantity += 1
    #         data.save()  #
    #     else:  # Inser to Shopcart
    #         data = ShopCart()  # model ile bağlantı kur
    #         data.user_id = current_user.id
    #         data.product_id = id
    #         data.quantity = 1
    #         data.save()  #
    #     messages.success(request, "Product added to Shopcart")
    #     return HttpResponseRedirect(url)


def shopcart(request):
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)

    # for rs in shopcart:
    #     rs.quantity = int(request.POST['quantity_in_shopcart'])

    # quantity_shopcart = int(request.POST['quantity_in_shopcart'])
    # print(quantity_shopcart)
    total = 0
    count = shopcart.count()

    for rs in shopcart:
        total += rs.price * rs.quantity

    context = {
        'shopcart': shopcart,
        'category': category,
        'total': total,
        'count': count,
        # 'quantity_shopcart': quantity_shopcart,
    }
    return render(request, 'shopcart_products.html', context)

@login_required(login_url='/login')  # Check login
def changefromcart(request, id):
    qty = request.POST['quantity_in_shopcart']
    sets = set(".,:;!_*-+()/#¤%&)").isdisjoint(qty)
    if qty == 0 or qty == '0' or qty == '' or sets == False:
        return HttpResponseRedirect("/shopcart")
    cart_product = ShopCart.objects.get(pk=id)
    cart_product.quantity = qty
    cart_product.save()
    messages.success(request, "Количество товара "+cart_product.product.title+' изменено')
    return HttpResponseRedirect("/shopcart")




@login_required(login_url='/login')  # Check login
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Товар удалён из корзины")
    return HttpResponseRedirect("/shopcart")


# @login_required(login_url='/login')  # Check login
# def delivery_form(request, id):
#     delivery = request.POST['delivery']
#     # cart_product = ShopCart.objects.get(pk=id)
#     # cart_product.quantity = qty
#     # cart_product.save()
#     # messages.success(request, "Количество товара "+cart_product.product.title+' изменено')
#     return HttpResponseRedirect("/shopcart")


def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 200
    for rs in shopcart:
        total += (rs.price * rs.quantity)

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        Order.delivery = request.POST['delivery']
        if Order.delivery == 'Самовывоз':
            total -= 200
        # return HttpResponse(request.POST.items())
        if form.is_valid():

            data = Order()
            data.first_name = form.cleaned_data['first_name']  # get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.email = form.cleaned_data['email']
            data.phone = form.cleaned_data['phone']
            data.delivery = form.cleaned_data['delivery']
            data.pay = form.cleaned_data['pay']
            data.user_id = current_user.id
            data.total = total
            ordercode = get_random_string(5).upper()  # random cod
            data.code = ordercode
            data.save()  #

            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id = data.id  # Order Id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                # if rs.product.variant == 'None':
                detail.price = rs.price
                detail.width = rs.width
                detail.height = rs.height
                # else:
                #     detail.price = rs.variant.price
                # detail.variant_id = rs.variant_id
                detail.amount = rs.amount
                detail.save()
                # ***Reduce quantity of sold product from Amount of Product
                # if rs.product.variant == 'None':
                product = Product.objects.get(id=rs.product_id)
                # product.amount -= rs.quantity
                product.save()
                # else:
                #     variant = Variants.objects.get(id=rs.product_id)
                #     variant.quantity -= rs.quantity
                #     variant.save()
                # ************ <> *****************

            ShopCart.objects.filter(user_id=current_user.id).delete()  # Clear & Delete shopcart
            request.session['cart_items'] = 0
            messages.success(request, "Ваш заказ сохранён")
            return render(request, 'order_completed.html', {'ordercode': ordercode, 'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    context = {'shopcart': shopcart,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile,
               }

    return render(request, 'order_form.html', context)

order/templates/order_completed.html
{% extends 'homebase.html' %}

{% load static %}

{% block title %} Заказ принят {% endblock title %}

{% block header %} {% include 'header.html' %} {% endblock header %} <!-- подсасывание из header.html -->

{% block body %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="shopcart-wrapper">
        <div class="shopcart">
            <div class="shopcart-title">
                <p>Заказ принят</p>
            </div>
            <div class="shopcart-title2" style="font-size: 24px">
                <p>{{ user.first_name }} {{ user.last_name }}</p>
                <p>Ваш заказ принят  </p>
                <p>Код заказа: {{ ordercode }}</p>
                <hr>
                <p> Спасибо </p>
                <p>  </p>
                <p>  </p>
                <hr>
            </div>
        </div>
    </div>

{% endblock body %} <!-- подсасывание из body.html -->

{% block footer %} {% include 'footer.html' %} {% endblock footer %} <!-- подсасывание из footer.html -->

order/templates/order_form.html
{% extends 'homebase.html' %}

{% load static %}

{% block title %} Оформление заказа {% endblock title %}

{% block header %} {% include 'header.html' %} {% endblock header %} <!-- подсасывание из header.html -->

{% block body %}

    <div id="breadcrumb">
        <div class="card-wrapper">
            <ul class="breadcrumb" style="display: flex">
                <li><a href="/">Главная</a></li>
                <li class="">/</li>
                <li class="">Оформление заказа</li>
            </ul>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="shopcart-wrapper">
        <div class="shopcart">
            <div class="shopcart-title">
                <p>Оформление заказа</p>
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <div class="shopcart_table">

                    <div class="shopcart_product">

                        <div class="order_form">
                            <p><label for="id_first_name">Имя:</label>
                                <input type="text" name="first_name" value="{{ user.first_name }}" class="input"
                                       maxlength="10" required="required" id="id_first_name">
                            </p>
                            <p><label for="id_last_name">Фамилия:</label>
                                <input type="text" name="last_name" value="{{ user.last_name }}" class="input"
                                       maxlength="10" required="required" id="id_last_name">
                            </p>
                            <p><label for="id_city">Город:</label>
                                <input type="text" required="required" name="city" class="input" id="id_city"
                                       value="{{ profile.city }}">
                            </p>
                            <p><label for="id_address">Адрес:</label>
                                <input type="text" required="required" name="address" value="{{ profile.address }}"
                                       class="input"
                                       maxlength="150" id="id_address">
                            </p>
                            <p><label for="id_email">Email:</label>
                                <input type="text" required="required" name="email" value="{{ profile.email }}"
                                       class="input"
                                       maxlength="100"
                                       id="id_email">
                            </p>
                            <p><label for="id_phone">Телефон:</label>
                                <input type="text" required="required" name="phone" value="{{ profile.phone }}"
                                       class="input" maxlength="20"
                                       id="id_phone">
                            </p>

                        </div>

                        <div class="shopcart_form">
                            <div class="shopcart-title2" style="font-size: 24px">
                                <p>Список товаров</p>
                            </div>
                            <table class="shopcart_product_table">
                                <thead>
                                <tr>
                                    <th class="h-product">
                                        Товар
                                    </th>
                                    <th class="h-title">

                                    </th>
                                    <th class="h-price">
                                        Цена
                                    </th>
                                    <th class="h-count">
                                        Кол-во
                                    </th>
                                    <th class="h-total">
                                        Итого
                                    </th>
                                    <th class="h-delete">

                                    </th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for rs in shopcart %}

                                    <tr>
                                        <td class="b-img_product">
                                            <img src="{{ rs.product.image.url }}" alt="">
                                        </td>
                                        <td class="b-title">
                                            <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{ rs.product }}</a>
                                            <ul>
                                                <li><span>Ширина: {{ rs.width }}</span></li>
                                                <li><span>Высота: {{ rs.height }}</span></li>
                                            </ul>
                                        </td>
                                        <td class="b-price">
                                        <span id="price">{{ rs.price }} <i class="fa fa-rub"
                                                                           aria-hidden="true"></i></span>
                                        </td>
                                        <td class="b-count">
                                            <p>{{ rs.quantity }}</p>
                                        </td>
                                        <td class="b-total">
                                        <span id="price">{{ rs.amount }} <i class="fa fa-rub"
                                                                            aria-hidden="true"></i></span>
                                        </td>
                                        {#                                        <td class="b-delete">#}
                                        {#                                            <a href="/order/deletefromcart/{{ rs.id }}"#}
                                        {#                                               onclick="return confirm('Удалить! Вы уверены?')">#}
                                        {#                                                <button class=""><i title="Удалить из корзины" class="fa fa-trash-o"#}
                                        {#                                                                    aria-hidden="true"></i></button>#}
                                        {#                                            </a>#}
                                        {#                                        </td>#}
                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>

                    <aside class="block_final_price">
                        <div class="block_final_price_title">
                            <p>Доставка</p>
                        </div>
                        <div class="block_final_price_count">

                            <script>


                                function react1() {
                                    var jopa = document.querySelector('#total_price_order');
                                    jopa.innerHTML = {{ total }};
                                }

                                function react2() {
                                    var jopa = document.querySelector('#total_price_order');
                                    jopa.innerHTML = {{ total }} - 200;
                                }
                            </script>

                            <input onchange="react1()" type="radio" checked name="delivery" id="dont_free_delivery"
                                   value="Курьер">
                            <span>Доставка<p>200р.</p> </span>
                            <input onchange="react2()" type="radio" name="delivery" id="free_delivery" value="Самовывоз">
                            <p>Самовывоз бесплатно</p>

                        </div>
                        <div class="block_final_price_title">
                            <p>Сумма заказа</p>
                        </div>
                        <div class="block_final_price_final">
                            <span id="total_price_order">{{ total }}</span><i class="fa fa-rub" aria-hidden="true"></i>
                        </div>
                        <div class="block_final_price_title">
                            <p>Оплата</p>
                        </div>
                        <div class="block_final_price_count">
                            <ul>
                                <li><input type="radio" name="pay" id="" checked="checked" value="Картой онлайн"> <span>Картой онлайн</span>
                                </li>
                                <li><input type="radio" name="pay" id="" value="При получении">
                                    <span>При получении</span></li>
                            </ul>
                        </div>
                        <div class="block_final_price_button">
                            {% if shopcart.count >= 1 %}
                                <a href="">
                                    <button type="submit" class="btn_checkout">Перейти к оплате</button>
                                </a>
                            {% endif %}
                        </div>

                    </aside>

                </div>
            </form>
        </div>
    </div>

{% endblock body %} <!-- подсасывание из body.html -->

{% block footer %} {% include 'footer.html' %} {% endblock footer %} <!-- подсасывание из footer.html -->

order/templates/shopcart_products.html
{% extends 'homebase.html' %}

{% load static %}

{% block title %} Корзина {% endblock title %}

{% block header %} {% include 'header.html' %} {% endblock header %} <!-- подсасывание из header.html -->

{% block body %}

    <div id="breadcrumb">
        <div class="card-wrapper">
            <ul class="breadcrumb" style="display: flex">
                <li><a href="/">Главная/</a></li>
                <li class="">Корзина</li>
            </ul>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="shopcart-wrapper">
        <div class="shopcart">
            <div class="shopcart-title">
                <p>Корзина</p>
            </div>
            <div class="shopcart_table">
                <div class="shopcart_product">
                    <table class="shopcart_product_table">
                        <thead>
                        <tr>
                            <th class="h-product">
                                Товар
                            </th>
                            <th class="h-title">

                            </th>
                            <th class="h-price">
                                Цена
                            </th>
                            <th class="h-count">
                                Кол-во
                            </th>
                            <th class="h-total">
                                Итого
                            </th>
                            <th class="h-delete">

                            </th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for rs in shopcart %}

                            <tr>
                                <td class="b-img_product">
                                    <img src="{{ rs.product.image.url }}" alt="">
                                </td>
                                <td class="b-title">
                                    <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{ rs.product}}</a>
                                    <ul>
                                        <li><span>Ширина: {{ rs.width }}</span></li>
                                        <li><span>Высота: {{ rs.height }}</span></li>
{#                                        <li><span>Подкладка: Без подкладки</span></li>#}
                                    </ul>
                                </td>
                                <td class="b-price">

                                    <span id="price">{{ rs.price }} <i class="fa fa-rub" aria-hidden="true"></i></span>
                                </td>
                                <form action="{% url 'changefromcart' id=rs.id%}" method="post">
                                    {% csrf_token %}
                                    <td class="b-count">
                                        <input id="jopa" class="input" type="number" min="1" name="quantity_in_shopcart" value="{{ rs.quantity }}" onchange="submit();">
{#                                        <input type="submit" value="ОК">#}
                                    </td>
                                </form>

                                <td class="b-total">
                                    <span id="price">{{ rs.amount }} <i class="fa fa-rub" aria-hidden="true"></i></span>
                                </td>
                                <td class="b-delete">
                                    <a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Удалить! Вы уверены?')">
                                        <button class=""><i title="Удалить из корзины" class="fa fa-trash-o"
                                                        aria-hidden="true"></i></button>
                                    </a>
                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>

                <aside class="block_final_price">
                    <div class="block_final_price_title">
                        <p>В корзине</p>
                    </div>
                    <div class="block_final_price_count">
                        <p>{{ shopcart.count }}</p>
                        <p id="title_count">товара</p>
                    </div>
                    <div class="block_final_price_final">
                        <span id="price">{{ total }} <i class="fa fa-rub" aria-hidden="true"></i></span>
                    </div>
                    <div class="block_final_price_button">
                         {% if shopcart.count >= 1 %}
                            <a href="/order/orderproduct">
                                <button type="button" class="btn_checkout">Перейти к оформлению</button>
                            </a>
                         {% endif %}
                    </div>
                </aside>
            </div>
        </div>
    </div>

{% endblock body %} <!-- подсасывание из body.html -->

{% block footer %} {% include 'footer.html' %} {% endblock footer %} <!-- подсасывание из footer.html -->